name: Resources
version: 1.1.0
main: exposed.hydrogen.resources.ResourcesSpigot
api-version: 1.18
load: STARTUP
authors: [ Hydrogen ]
description: Resource pack server using unnamed team's creative api
